export const SOCKET_CONNECT = 'connect';
export const SOCKET_DISCONNECT = 'disconnect';

export const IO_SIGNIN = 'AUTH:SIGNIN';
export const IO_SIGNOUT = 'AUTH:SIGNOUT';
export const IO_NEW_USER = 'AUTH:NEW_USER';

export const IO_GET_INITIAL_DATA = 'CHAT:GET_INITIAL_DATA';
export const IO_PRIVATE_CHANNEL_CREATED = 'CHAT:PRIVATE_CHANNEL_CREATED';
export const IO_GROUP_CHANNEL_CREATED = 'CHAT:GROUP_CHANNEL_CREATED';
export const IO_REMOVED_FROM_GROUP_CHANNEL = 'CHAT:REMOVED_FROM_GROUP_CHANNEL';
export const IO_GROUP_CHANNEL_UPDATED = 'CHAT:GROUP_CHANNEL_UPDATED';
export const IO_MESSAGES_RECEIVED = 'CHAT:MESSAGES_RECEIVED';
export const IO_SET_ACTIVE_CHANNEL = 'CHAT:SET_ACTIVE_CHANNEL';
export const IO_SET_LAST_SEEN = 'CHAT:SET_LAST_SEEN';
export const IO_USER_STATUS_CHANGED = 'CHAT:USER_STATUS_CHANGED';
export const IO_USER_THOUGHTS_CHANGED = 'CHAT:USER_THOUGHTS_CHANGED';
