export const SOCKET_CONNECT = 'connect';
export const SOCKET_DISCONNECT = 'disconnect';
export const IO_SIGNIN = 'AUTH:SIGNIN';
export const IO_SIGNOUT = 'AUTH:SIGNOUT';
export const IO_GET_INITIAL_DATA = 'CHAT:GET_INITIAL_DATA';
export const IO_PRIVATE_CHANNEL_CREATED = 'CHAT:PRIVATE_CHANNEL_CREATED';
export const IO_GROUP_CHANNEL_CREATED = 'CHAT:GROUP_CHANNEL_CREATED';
